In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from gensim.models import Word2Vec

In [2]:
data = pd.read_excel(r'Assignment_Data.xlsx')

In [3]:
data.head()

,Unnamed: 0,Query Id,Query Name,Date,Title,Snippet,Full Text,Url,Domain,Sentiment,...,Twitter Following,Twitter Reply Count,Twitter Reply to,Twitter Retweet of,Twitter Retweets,Twitter Tweets,Twitter Verified,Word Count,mozRank Score,Reach (new)
0,1,1999658222,Gilead query,2018-12-31 21:45:23.000,2018 has been a poignantly difficult year for ...,...passed likely due to pregnancy complication...,2018 has been a poignantly difficult year for ...,https://strongbrew.ca/post/181593013651,strongbrew.ca,neutral,...,0,0,NaN,NaN,0,0,False,NaN,0.00,0.0
1,2,1999658222,Gilead query,2018-12-31 10:04:00.000,Corrine Graves â™ŠðŸŽ¶ (@Corrrine): RT @StairwayNow...,RT @StairwayNowhere: In 2018 I've beaten pneum...,RT @StairwayNowhere: In 2018 I've beaten pneum...,http://twitter.com/Corrrine/statuses/107967955...,twitter.com,neutral,...,2981,0,NaN,http://twitter.com/StairwayNowhere/statuses/10...,0,62094,False,NaN,9.60,1341.0
2,3,1999658222,Gilead query,2018-12-31 04:08:23.000,Derek Beaton (@derek__beaton): RT @TheFastestE...,RT @TheFastestEddie: I need your help to get i...,RT @TheFastestEddie: I need your help to get i...,http://twitter.com/derek__beaton/statuses/1079...,twitter.com,neutral,...,327,0,NaN,http://twitter.com/TheFastestEddie/statuses/10...,0,2078,False,NaN,9.60,0.0
3,4,1999658222,Gilead query,2018-12-31 00:00:00.000,Ling's Design Studio: Season's Giving Blog Hop,...this hop is every single blog that particip...,"Monday, December 31, 2018\n\nSeason's Giving B...",http://lingshappyplace.blogspot.com/2018/12/se...,lingshappyplace.blogspot.com,neutral,...,0,0,NaN,NaN,0,0,False,NaN,3.93,0.0
4,5,1999658222,Gilead query,2018-12-29 09:14:56.000,Antisense Oligonucleotides - Antineoplastic ag...,...available. Other ongoing clinical trials in...,Home\n\n> Antineoplastic agents > Antisense Ol...,https://www.pocketdrugguide.com/antineoplastic...,www.pocketdrugguide.com,neutral,...,0,0,NaN,NaN,0,0,False,NaN,0.00,0.0

In [4]:
data['Sentiment'].value_counts()

neutral     2179
positive     151
negative      51
Name: Sentiment, dtype: int64

In [5]:
data['Query Id'].value_counts()

1999658222    2381
Name: Query Id, dtype: int64

In [6]:
data.drop('Unnamed: 0' , inplace = True , axis = 1)

In [7]:
data.describe()

,Query Id,Notes,Assignment,Average Pages per Visitor,Average Visits per Visitor,Backlinks,Blog Comments,Category Details,Engagement Score,Facebook Author ID,...,Twitter Author ID,Twitter Channel Role,Twitter Followers,Twitter Following,Twitter Reply Count,Twitter Retweets,Twitter Tweets,Word Count,mozRank Score,Reach (new)
count,2.381000e+03,0.0,0.0,2381.000000,2381.000000,2.381000e+03,2381.0,0.0,2381.000000,0.0,...,9.160000e+02,0.0,2381.000000,2381.000000,2381.000000,2381.000000,2.381000e+03,0.0,2381.000000,2365.000000
mean,1.999658e+09,NaN,NaN,8.746745,2.825703,1.943243e+07,0.0,NaN,0.049972,NaN,...,1.811064e+17,NaN,1078.146577,557.448971,0.055859,0.211256,1.075473e+04,NaN,4.855162,716.803383
std,0.000000e+00,NaN,NaN,10.551122,2.939350,2.408333e+07,0.0,NaN,0.668746,NaN,...,3.579277e+17,NaN,6684.475397,2116.747706,0.825937,3.302198,4.265611e+04,NaN,4.397598,2702.191655
min,1.999658e+09,NaN,NaN,0.000000,0.000000,0.000000e+00,0.0,NaN,0.000000,NaN,...,1.657961e+06,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000
25%,1.999658e+09,NaN,NaN,0.000000,0.000000,0.000000e+00,0.0,NaN,0.000000,NaN,...,1.749995e+08,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000
50%,1.999658e+09,NaN,NaN,0.000000,1.000000,7.300000e+01,0.0,NaN,0.000000,NaN,...,6.083699e+08,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,5.150000,0.000000
75%,1.999658e+09,NaN,NaN,22.000000,6.000000,4.985073e+07,0.0,NaN,0.000000,NaN,...,3.317022e+09,NaN,263.000000,327.000000,0.000000,0.000000,3.679000e+03,NaN,9.600000,197.000000
max,1.999658e+09,NaN,NaN,22.000000,20.000000,4.985073e+07,0.0,NaN,20.000000,NaN,...,1.074409e+18,NaN,189874.000000,53419.000000,29.000000,113.000000,1.240432e+06,NaN,9.600000,74529.000000

In [8]:
nan_cols = data.isnull().sum().sort_values(ascending = False)[:20].index
data.drop(nan_cols , inplace = True , axis = 1)

In [9]:
data.isnull().sum().sort_values(ascending = False)[:33]

City                     1910
City Code                1910
Author City Code         1842
Author City              1842
County Code              1789
County                   1789
Author County Code       1774
Author County            1774
Interest                 1773
Twitter Retweet of       1725
Media URLs               1720
Author State Code        1717
Author State             1717
State                    1660
State Code               1660
Display URLs             1642
Short URLs               1642
Expanded URLs            1642
Thread Author            1624
Mentioned Authors        1534
Account Type             1488
Twitter Author ID        1465
Full Name                1436
Avatar                   1395
Tags                     1302
Thread Entry Type        1142
Author                   1041
Author Continent         1009
Author Continent Code    1009
Author Country           1009
Author Country Code      1009
Author Location          1009
Gender                     57
dtype: int64

In [10]:
dlt_cols = ['City Code','Author City Code','County Code','Author County Code',
           'Twitter Retweet of','Media URLs','Author State Code','State Code',
           'Display URLs','Short URLs','Expanded URLs','Mentioned Authors',
            'Account Type','Twitter Author ID','Full Name','Avatar','Tags',
           'Thread Entry Type','Author Continent Code','Author Country Code']
data.drop(dlt_cols , inplace = True , axis = 1)

In [11]:
data.isnull().sum().sort_values(ascending = False)[:15]

City                1910
Author City         1842
County              1789
Author County       1774
Interest            1773
Author State        1717
State               1660
Thread Author       1624
Author              1041
Author Location     1009
Author Country      1009
Author Continent    1009
Gender                57
Reach (new)           16
Starred                0
dtype: int64

In [12]:
auth_dlts_cols = ['Author','Author City','Author County','Author State','Author Location']
data.drop(auth_dlts_cols , inplace = True , axis = 1)

In [13]:
pd.set_option('display.max_rows',None)

In [14]:
unique_cols = []

for col in data.columns:
    if (data[col].nunique() == 1):
        unique_cols.append(col)
        
data.drop(unique_cols , inplace = True , axis = 1)

In [15]:
ext_dlt_cols = ['Title','Snippet','Url','Author Continent','Author Country','Backlinks',
'Resource Id','Thread Author','Thread Id','Twitter Following','Twitter Reply Count',
'Twitter Retweets','Twitter Tweets']
data.drop(ext_dlt_cols , inplace = True , axis = 1)

In [16]:
data.isnull().sum()

Date                             0
Full Text                        0
Domain                           0
Sentiment                        0
Page Type                        0
Country Code                     0
Continent Code                   0
Continent                        0
Country                          0
Average Pages per Visitor        0
Average Visits per Visitor       0
City                          1910
County                        1789
Engagement Score                 0
Forum Posts                      0
Forum Views                      0
Gender                          57
Impact                           0
Impressions                      0
Instagram Comments               0
Instagram Likes                  0
Interest                      1773
Kred Influence                   0
Kred Outreach                    0
Latitude                         0
Longitude                        0
Minutes per Visitor              0
Percentage Female                0
Percentage Male                  0
Twitter Reach                    0
State                         1660
Total Monthly Visitors           0
Twitter Followers                0
Twitter Verified                 0
mozRank Score                    0
Reach (new)                     16
dtype: int64

In [17]:
more_dlt_cols = ['City','County','State','Interest']
data.drop(more_dlt_cols , inplace = True , axis = 1)

In [18]:
data['Reach (new)'].fillna(value = data['Reach (new)'].mean() , inplace=True)

In [19]:
data['Gender'].fillna(value = 'unknown' , inplace=True)

In [20]:
df = data.copy()

In [21]:
df.shape

(2381, 32)

In [22]:
df.isnull().sum()

Date                          0
Full Text                     0
Domain                        0
Sentiment                     0
Page Type                     0
Country Code                  0
Continent Code                0
Continent                     0
Country                       0
Average Pages per Visitor     0
Average Visits per Visitor    0
Engagement Score              0
Forum Posts                   0
Forum Views                   0
Gender                        0
Impact                        0
Impressions                   0
Instagram Comments            0
Instagram Likes               0
Kred Influence                0
Kred Outreach                 0
Latitude                      0
Longitude                     0
Minutes per Visitor           0
Percentage Female             0
Percentage Male               0
Twitter Reach                 0
Total Monthly Visitors        0
Twitter Followers             0
Twitter Verified              0
mozRank Score                 0
Reach (new)                   0
dtype: int64

In [23]:
pd.set_option('display.max_columns',None)

In [24]:
df.head()

,Date,Full Text,Domain,Sentiment,Page Type,Country Code,Continent Code,Continent,Country,Average Pages per Visitor,Average Visits per Visitor,Engagement Score,Forum Posts,Forum Views,Gender,Impact,Impressions,Instagram Comments,Instagram Likes,Kred Influence,Kred Outreach,Latitude,Longitude,Minutes per Visitor,Percentage Female,Percentage Male,Twitter Reach,Total Monthly Visitors,Twitter Followers,Twitter Verified,mozRank Score,Reach (new)
0,2018-12-31 21:45:23.000,2018 has been a poignantly difficult year for ...,strongbrew.ca,neutral,blog,ca,n-a,North America,Canada,0,0,0.0,0,0,unknown,15,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,False,0.00,0.0
1,2018-12-31 10:04:00.000,RT @StairwayNowhere: In 2018 I've beaten pneum...,twitter.com,neutral,twitter,ca,n-a,North America,Canada,22,6,0.0,0,0,female,49,2189,0,0,734,7,0.0,0.0,20,46,54,734,6000000000,2189,False,9.60,1341.0
2,2018-12-31 04:08:23.000,RT @TheFastestEddie: I need your help to get i...,twitter.com,neutral,twitter,ca,n-a,North America,Canada,22,6,0.0,0,0,male,35,248,0,0,512,0,0.0,0.0,20,46,54,512,6000000000,248,False,9.60,0.0
3,2018-12-31 00:00:00.000,"Monday, December 31, 2018\n\nSeason's Giving B...",lingshappyplace.blogspot.com,neutral,blog,us,n-a,North America,United States,0,0,0.0,0,0,unknown,45,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,False,3.93,0.0
4,2018-12-29 09:14:56.000,Home\n\n> Antineoplastic agents > Antisense Ol...,www.pocketdrugguide.com,neutral,blog,us,n-a,North America,United States,0,0,0.0,0,0,unknown,15,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,False,0.00,0.0

In [25]:
df.drop(['Country Code','Continent Code','Average Visits per Visitor',
'Engagement Score', 'Forum Posts','Forum Views','Instagram Comments',
 'Instagram Likes', 'Kred Influence', 'Kred Outreach','Latitude','Longitude',
 'Minutes per Visitor','Total Monthly Visitors','Twitter Followers',
 'Twitter Verified','mozRank Score','Reach (new)'
],axis = 1 , inplace = True)

In [26]:
df.head()

,Date,Full Text,Domain,Sentiment,Page Type,Continent,Country,Average Pages per Visitor,Gender,Impact,Impressions,Percentage Female,Percentage Male,Twitter Reach
0,2018-12-31 21:45:23.000,2018 has been a poignantly difficult year for ...,strongbrew.ca,neutral,blog,North America,Canada,0,unknown,15,0,0,0,0
1,2018-12-31 10:04:00.000,RT @StairwayNowhere: In 2018 I've beaten pneum...,twitter.com,neutral,twitter,North America,Canada,22,female,49,2189,46,54,734
2,2018-12-31 04:08:23.000,RT @TheFastestEddie: I need your help to get i...,twitter.com,neutral,twitter,North America,Canada,22,male,35,248,46,54,512
3,2018-12-31 00:00:00.000,"Monday, December 31, 2018\n\nSeason's Giving B...",lingshappyplace.blogspot.com,neutral,blog,North America,United States,0,unknown,45,0,0,0,0
4,2018-12-29 09:14:56.000,Home\n\n> Antineoplastic agents > Antisense Ol...,www.pocketdrugguide.com,neutral,blog,North America,United States,0,unknown,15,0,0,0,0

In [27]:
df.drop(['Impressions','Average Pages per Visitor'] , axis = 1 , inplace = True)

In [28]:
df.head()

,Date,Full Text,Domain,Sentiment,Page Type,Continent,Country,Gender,Impact,Percentage Female,Percentage Male,Twitter Reach
0,2018-12-31 21:45:23.000,2018 has been a poignantly difficult year for ...,strongbrew.ca,neutral,blog,North America,Canada,unknown,15,0,0,0
1,2018-12-31 10:04:00.000,RT @StairwayNowhere: In 2018 I've beaten pneum...,twitter.com,neutral,twitter,North America,Canada,female,49,46,54,734
2,2018-12-31 04:08:23.000,RT @TheFastestEddie: I need your help to get i...,twitter.com,neutral,twitter,North America,Canada,male,35,46,54,512
3,2018-12-31 00:00:00.000,"Monday, December 31, 2018\n\nSeason's Giving B...",lingshappyplace.blogspot.com,neutral,blog,North America,United States,unknown,45,0,0,0
4,2018-12-29 09:14:56.000,Home\n\n> Antineoplastic agents > Antisense Ol...,www.pocketdrugguide.com,neutral,blog,North America,United States,unknown,15,0,0,0

In [29]:
df.drop('Domain',axis = 1, inplace = True)

In [30]:
df.head()

,Date,Full Text,Sentiment,Page Type,Continent,Country,Gender,Impact,Percentage Female,Percentage Male,Twitter Reach
0,2018-12-31 21:45:23.000,2018 has been a poignantly difficult year for ...,neutral,blog,North America,Canada,unknown,15,0,0,0
1,2018-12-31 10:04:00.000,RT @StairwayNowhere: In 2018 I've beaten pneum...,neutral,twitter,North America,Canada,female,49,46,54,734
2,2018-12-31 04:08:23.000,RT @TheFastestEddie: I need your help to get i...,neutral,twitter,North America,Canada,male,35,46,54,512
3,2018-12-31 00:00:00.000,"Monday, December 31, 2018\n\nSeason's Giving B...",neutral,blog,North America,United States,unknown,45,0,0,0
4,2018-12-29 09:14:56.000,Home\n\n> Antineoplastic agents > Antisense Ol...,neutral,blog,North America,United States,unknown,15,0,0,0

In [31]:
import re

In [32]:
def find_lymphoma(x):
    if re.search('lymphoma',x):
        return True
    else:
        return False

In [33]:
df['is_lymphoma'] = df['Full Text'].apply(find_lymphoma)

In [34]:
def find_hodgkin(x):
    x = x.lower()
    if re.search(r'hodgkin',x):
        return True
    else:
        return False

In [35]:
df['is_hodgkin'] = df['Full Text'].apply(find_hodgkin)

In [36]:
df_hodgkin = df[df['is_hodgkin']].copy()
df_hodgkin.shape

(910, 13)

In [37]:
df.drop('is_lymphoma' , inplace = True , axis = 1)

In [38]:
df.to_csv('cleaned_data.csv')